### ISSUE TITLE
Enhance with configurable Parralleism

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/Serilog.Sinks.Async#5]
As well as Stephen Cleary's book 'Concurrency in C# Cookbook', I have been studying the book 'TPL DataFlow by Example' (by Mark Carkci) and it recommends the following:

_**Prevent Large Buffers**: You must be mindful of the rate of incoming data to the rate of processing that data in a block. A high rate of incoming data combined with a slow process could create a large backlog of data in the buffer. To reduce the likelihood of this situation either increase the MaxDegreeOfParallelism or add more blocks to process the incoming data. But remember that these solutions could also cause the data to be returned in a different order than they arrived. If maintaining order is required, consider using a BatchBlock to group together multiple data items to be processed at one time._

So we might benefit by:

1. Adding an ActionBlock<T> to the output of the BufferBlock<T> we already have. This can simply process the message by forwarding to the delegate sink. (Done in https://github.com/jezzsantos/Serilog.Sinks.Async/commit/7f951c06c09b13a9a35fd682c863a569a366f06f)
2. Then we could increase the 'MaxDegreeOfParallelism' and recruit more cores to process the log events, simply. This could then be configured on the sink.
3. We could use the BatchBlock<T> to process batches of log events for sinks that want to support that?

Thoughts?

**Comment by nblumhardt** [comment]
Hey Jezz, just some quick thoughts-

Increasing parallelism may not necessarily help here as the workload is frequently I/O bound, and even when not, the contention around things like file locks could be a problem with more than one thread per sink.

Thinking some more about the "async waits" you mention, since the logging API is synchronous, this will still end up as a blocked thread when the buffer is full (we'll have to call `.Wait()` in `Emit()`). Using an `async void` method like this one:

https://github.com/jezzsantos/Serilog.Sinks.Async/blob/master/src/Serilog.Sinks.Async/BufferedQueueSink.cs#L36

...will end up leaving a continuation on the heap per event, so (if I understand correctly) will be less memory efficient than adding the event to the queue would be.

When I last faced this problem (Seq's internal channels) I ended up concluding that, if the goal is to keep the application up at all costs, dropping events when the queue becomes full is the only viable strategy. Any other will require storage either explicitly, or implicitly through blocking threads.

Perhaps using a queue (perhaps `BlockingCollection`) and single worker thread per sink would be an easier option to reason about than the TPL and async in this case? Probably worth considering, though of course there are trade-offs in all directions :-) Just thought I'd throw another option out there.

HTH!

**Comment by jezzsantos** [comment]
I think you are right on most counts.

My understanding with the `BufferBlock<T>` that since we do `await queue.SendAsync()` that call will async-block the calling thread until the queue has space on it (the thread can do other things during that time), then the task will complete when the item is queued.

So at worst case, the calling thread will wait as long as if it was a regular synchronous call doing the sinking itself. But this is only the case if the buffer is full. If not then the call returns immediately.

Different systems are going to have different loads and varying bottlenecks no doubt so we simply can't judge its effectiveness form teh outside without knowing the system in detail. We are never going to know that for all use cases.

I guess, people using this sink need to be aware that at worst case, it takes same time as sync call, but if consumption is fast enough, or has caught up with production, then they get a significant performance gain. 

The only way to get more benefit is to either reserve more memory for the buffers or have parrallel threads doing the sinking, and as you say that may cause IO contention with some sinks. Certainly not all though.
 
For example in our usage our IO sink is a message queue, and writing to that queue is thread safe, so parrallel writing is going to work for us, and probably others too. It costs an extra thread, which is another trade off (especially in a web server app).

I think the best thing to do is document the trade offs, offer any options to tweet those trade offs and let users decide themselves. If there is value in it users will decide themselves.

It's all trade offs and setting the right expectations from the get go.

**Comment by jezzsantos** [comment]
Considering  #6 in this discussion and reflecting on multi-threading, it is becoming clearer to me that the only viable opportunity for parallelism is in dispatching buffered/queued log events to multiple instances of the delegated sink, so that we reduce the chance of filling up the buffered queue.

If we made that configurable by the developer, would that help?

There is some native parrallelism in the BufferBlock<T> already, and some more in the ActionBlock<T> if we hook them up together.

**Comment by nblumhardt** [comment]
Hey, thanks for the detailed reply.

> ... since we do await queue.SendAsync() that call will async-block the calling thread until the queue has space on it .... Then the task will complete when the item is finally queued.

Yes, this is the problem, I think. The goal of limiting the buffer size is to prevent RAM exhaustion, but, if we block (async or otherwise) then the event we were going to enqueue is still in RAM, and we've added a bunch of bookkeeping info that's needed in order for the wait (or block) to resume. So instead of the event costing one queue entry, we've added an async statemachine instance with local variable information (including the event) and continuation info.

**Comment by jezzsantos** [comment]
Agreed. There is always a trade off

**Comment by jezzsantos** [comment]
Not sure we are getting anywhere here now.

The latest implementation uses `BufferBlock<T>` + `ActionBlock<T>` which makes it more maintainable and gets rid of the while loops. I am not sure how much simpler it could be?

In the context of what we are doing here (see #8 for a summary of the goals), we are trying to achieve the following:

* Decouple the submission of the log data from the writing to the sink of the log data. The sink could be a queue, a file system, a database etc. It could be heavily I/O bound (in the scenarios we are optimizing)
* Increase the responsiveness of the thread that calls the `ILog.*` methods, so it does not wait around for the actual sink to finish writing the data.
* Have some kind of memory buffer so that we don't fill up the available memory of the running process.
* Allow the developer to control the buffer size, and any parallelism they decide is available/good for their environment.

**Comment by jezzsantos** [comment]
Moving this discussion over to #8

**Comment by nblumhardt** [comment]
Hey, yes, seems tricky to get onto the same page without a whiteboard :-)

I only meant to comment on:

> Have some kind of memory buffer so that we don't fill up the available memory of the running process.

(I think on the other points we're pretty much in sync.)

To make sure the amount of memory used by the sink is bounded, I don't think we can just `await` on adding to the fixed sized buffer. While it'll limit the amount of memory consumed by the buffer, every `await` call that is blocking will create a heap-allocated record that is larger than the one we are trying to save in the buffer.

Because the `await` doesn't itself apply any backpressure to slow the app down (nothing is waiting on _it_) I think this will result in the bounded-buffer approach actually consuming unbounded memory _faster_ than if we just enqueued the event in the buffer to start with.

Hence (if I'm correct, which is never a sure thing :-) ) I think we need a different strategy to meet goal number three in your list - one which works, at the cost of some lost events, is to drop events when the buffer gets full, rather than `await`-ing to add them.

Put another way, unless the sink drops events when the buffer fills up, it'll continue to consume more memory (the events that are waiting to go into the buffer have to be stored somewhere).

Hope this is a better formulation of what I was attempting to say, but if I'm missing the mark let me know.

Will move to #8 also. Cheers!
